### ISSUE TITLE
md5sum for SUSE-Linux-Enterprise-Server-15-SP1.x86_64-15.1.vagrant.libvirt.box file

### ISSUE THREAD

**Issue by alexarnoldy** [sigsteve/vagrant-caasp#11]
I'm getting a ton of errors during deployment for the skuba, kubectl, and helm commands not found. I'm wondering if I'm using the correct base box. Can you please provide the md5sum here for the base box to validate.

Thanks!

**Comment by alexarnoldy** [comment]
Turns out I hadn't read the email that pointed me to the image on filr. Using the correct image seems to help a bunch!

I still think having the image md5sum here would help troubleshooting issues around image quality.

**Comment by sigsteve** [comment]
The md5 currently is d1a324ead3610bfcf0f0f994771e7ba2.
Once some updates to kiwi are in, we will get this into OBS.

**Comment by ne0777** [comment]
Latest md5 for the recent beta4 build is:
8eaa6d79adf6fce758259f0a9842ecfa

**Comment by sigsteve** [comment]
The vagrant box can now be found in IBS, along with relevant metadata.
https://build.suse.de/package/binaries/home:sbecht:vc-test:SLE-15-SP1/Vagrant-SLE-15-SP1-CAASP4:libvirt/images
