### ISSUE TITLE
Add stop/start functionality

### ISSUE THREAD

**Issue by sigsteve** [sigsteve/vagrant-caasp#14]
We need to have the ability to shutdown and bring up a cluster that's already been deployed.

**Comment by SweBarre** [comment]
Hi, 
I do have a start and a stop script for the cluster
I haven't pushed it though, don't know exactly how it should be implemented.

Should it be a complete new script (I think so, it doesn't make sense too me to have it as an option to deploy_caasp.sh)
Should it be two scripts, eg. cluster_start.sh and cluster_stop.sh or one script with a start/stop parameter?

Cheers

**Comment by SweBarre** [comment]
I also experience some issues when deploying a cluster, not always though.
But sometimes it can take several minutes for the masters and workers to reach Ready state.
And if the workers are not in "Ready" state the Dashboard fails to install (and sometimes tiller aswell).

So I also included wait_for_masters_ready and wait_for_workers_ready in the 04.add_workers.sh so the deployment won't continue until all cluster nodes has reached Ready state.

I pushed my rough scripts to my fork https://github.com/SweBarre/vagrant-caasp/commit/b0ba6abc1551d8ab68e2b7b52b042d7abdd0c0e7

You can take a look at it and give some feedback on what you think.
```
./cluster.sh -h
Usage cluster.sh [options..] [command]
-v, --verbose        Make the operation more talkative
-h,-?, --help        Show help and exit

start                start a previosly provisioned cluster
stop                 stop a running cluster

getToken             get Dashboard token
```
