### ISSUE TITLE
Enable swap accounting

### ISSUE THREAD

**Issue by jandubois** [sigsteve/vagrant-caasp#22]
Enabling the `swapaccount=1` boot option is a prerequisite for CAP, at least when installing with the Diego scheduler, so can this be added to the vagrant-caasp box?

**Comment by ne0777** [comment]
The latest box (for beta4) contains this boot option.  From what I learned from @sigsteve you have worked together to verify?  If so can you close the issue?  Thanks!

**Comment by jandubois** [comment]
Yes, works great! Thanks for the quick turnaround!
