### ISSUE TITLE
 firewalld documentation

### ISSUE THREAD

**Issue by SweBarre** [sigsteve/vagrant-caasp#3]
The documentation lacks instructions that  firewalld needs to accept NFS connections (or to disable the firewalld).

Cheers

**Comment by sigsteve** [comment]
Where are you seeing firewall running, or what issue are you hitting?
We shouldn't have the firewall enabled anywhere.

**Comment by SweBarre** [comment]
that's on the KVM host, not the guests.

**Comment by SweBarre** [comment]
fixed https://github.com/sigsteve/vagrant-caasp/commit/d1d382e9a8272503904cea778e0aad8e0465386
