### ISSUE TITLE
Vagrant 2.2.6 on openSUSE

### ISSUE THREAD

**Issue by mmontecchi** [sigsteve/vagrant-caasp#76]
Hi,
today my openSUSE upgrades Vagrant to 2.2.6.
Try to install vagrant-libvirt this is the error:
Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
Traceback (most recent call last):
	18: from /usr/share/vagrant/gems/bin/vagrant:23:in `<main>'
	17: from /usr/share/vagrant/gems/bin/vagrant:23:in `load'
	16: from /usr/share/vagrant/gems/gems/vagrant-2.2.6/bin/vagrant:166:in `<top (required)>'
	15: from /usr/share/vagrant/gems/gems/vagrant-2.2.6/lib/vagrant/environment.rb:290:in `cli'
	14: from /usr/share/vagrant/gems/gems/vagrant-2.2.6/lib/vagrant/cli.rb:66:in `execute'
	13: from /usr/share/vagrant/gems/gems/vagrant-2.2.6/plugins/commands/plugin/command/root.rb:66:in `execute'
	12: from /usr/share/vagrant/gems/gems/vagrant-2.2.6/plugins/commands/plugin/command/install.rb:69:in `execute'
	11: from /usr/share/vagrant/gems/gems/vagrant-2.2.6/plugins/commands/plugin/command/install.rb:69:in `each'
	10: from /usr/share/vagrant/gems/gems/vagrant-2.2.6/plugins/commands/plugin/command/install.rb:70:in `block in execute'
	 9: from /usr/share/vagrant/gems/gems/vagrant-2.2.6/plugins/commands/plugin/command/base.rb:14:in `action'
	 8: from /usr/share/vagrant/gems/gems/vagrant-2.2.6/lib/vagrant/action/runner.rb:102:in `run'
	 7: from /usr/share/vagrant/gems/gems/vagrant-2.2.6/lib/vagrant/util/busy.rb:19:in `busy'
	 6: from /usr/share/vagrant/gems/gems/vagrant-2.2.6/lib/vagrant/action/runner.rb:102:in `block in run'
	 5: from /usr/share/vagrant/gems/gems/vagrant-2.2.6/lib/vagrant/action/builder.rb:116:in `call'
	 4: from /usr/share/vagrant/gems/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
	 3: from /usr/share/vagrant/gems/gems/vagrant-2.2.6/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
	 2: from /usr/share/vagrant/gems/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
	 1: from /usr/share/vagrant/gems/gems/vagrant-2.2.6/plugins/commands/plugin/action/install_gem.rb:30:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.2.6/lib/vagrant/plugin/manager.rb:156:in `install_plugin': undefined method `name' for nil:NilClass (NoMethodError)

**Comment by sigsteve** [comment]
Did you run the script libvirt_setup/openSUSE_vagrant_setup.sh?

While I'm not exactly sure what is wrong there, after upgrading I typically have to run 'vagrant plugin expunge --reinstall'. There's also a step in the install script above that needs to be run (mv /opt/vagrant/embedded/lib/libreadline.so.7{,.disabled} | true), otherwise the build will fail.

If this doesn't work, let me know and I'd be happy to setup a quick meeting to get this fixed for you.

**Comment by mmontecchi** [comment]
Remember that my openSUSE upgrades to vagrant 2.2.6.
I will try with your suggestion: 'vagrant plugin expunge --reinstall'
Or better I will downgrade vagrant to 2.2.5.
Thanks

**Comment by alexrenna** [comment]
you can install latest vagrant from here: https://github.com/SUSE/sesdev#install-vagrant

**Comment by mmontecchi** [comment]
> you can install latest vagrant from here: https://github.com/SUSE/sesdev#install-vagrant

Thanks Alex
